#!/usr/bin/env python3
"""
Generate a large pool of non-intent bearing statements (noise pool).

These sentences do NOT map to any of the 150 CLINC150 intents.
They are natural language utterances that a user might say alongside
their actual intent-bearing queries.

This is lightweight (no LLMs): we use templates and programmatic variation
to generate thousands of unique non-intent statements.

Output: data/noise_pool.json
"""

import json
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
OUTPUT = SCRIPT_DIR / "data" / "noise_pool.json"

# Politeness markers (allowed, not intents)
POLITE = [
    "Can you",
    "Could you",
    "Please",
    "I want",
    "I'd like",
    "Would you",
    "Will you",
    "Do you think you could",
    "I'm wondering if you can",
    "Hey, can you",
    "Excuse me, can you",
    "By the way,",
    "Also,",
    "Oh, and",
    "And also",
    "One more thing,",
    "Additionally,",
    "Furthermore,",
    "Moreover,",
    "Plus,",
]

# Non-intent topics (general chitchat, filler, opinions, feelings)
# None of these map to CLINC150's 150 intents
NON_INTENT_TOPICS = [
    "the weather is really nice today",
    "I had a great breakfast this morning",
    "my favorite color is blue",
    "I love listening to music in the evening",
    "the movie last night was fantastic",
    "I'm feeling a bit tired today",
    "my dog loves playing in the park",
    "the coffee at that place is excellent",
    "I enjoy reading books before bed",
    "the flowers in my garden are blooming",
    "I'm thinking about learning guitar",
    "my friend is visiting next week",
    "the sunset was absolutely gorgeous",
    "I need to go grocery shopping later",
    "my favorite season is autumn",
    "I stayed up too late last night",
    "the park is peaceful in the morning",
    "I just finished a great workout",
    "my favorite food is Italian cuisine",
    "I love spending time with my family",
    "the stars were bright last night",
    "I'm planning a trip to the mountains",
    "my favorite hobby is painting",
    "the concert was absolutely amazing",
    "I had a long day at work",
    "my favorite movie is a classic",
    "I love cooking on weekends",
    "the beach was crowded yesterday",
    "my cat is very friendly",
    "I need to clean my room",
    "the library has many interesting books",
    "I'm baking a cake for the party",
    "my favorite dessert is chocolate cake",
    "I watched a documentary about space",
    "the museum has a new exhibition",
    "I'm trying to eat healthier these days",
    "my favorite band is coming to town",
    "I love walking in the rain",
    "the garden looks lovely this season",
    "I'm learning a new language",
    "my favorite sport is tennis",
    "I enjoy yoga in the morning",
    "the pizza at that place is delicious",
    "I'm reading a fascinating novel",
    "my favorite drink is green tea",
    "I love stargazing on clear nights",
    "the hike was challenging but rewarding",
    "I'm planning a surprise for my friend",
    "my favorite subject in school was history",
    "I enjoy photography as a hobby",
    "the concert tickets were expensive",
    "I'm trying to learn to cook Thai food",
    "my favorite animal is a dolphin",
    "I love visiting museums on weekends",
    "the traffic was terrible this morning",
    "I'm redecorating my living room",
    "my favorite flower is a rose",
    "I enjoy listening to jazz music",
    "the road trip was incredible",
    "I'm learning to play the piano",
    "my favorite fruit is mango",
    "I love trying new restaurants",
    "the sunset at the beach was magical",
    "I'm training for a marathon",
    "my favorite ice cream flavor is vanilla",
    "I enjoy watching documentaries",
    "the bookstore around the corner is charming",
    "I'm planning a weekend getaway",
    "my favorite type of bread is sourdough",
    "I love watching sunsets",
    "the farmers market has fresh produce",
    "I'm starting a new workout routine",
    "my favorite nut is almonds",
    "I enjoy visiting art galleries",
    "the chocolate cake was heavenly",
    "I'm planting a vegetable garden",
    "my favorite cheese is cheddar",
    "I love going to the theater",
    "the hiking trail was beautiful",
    "I'm learning to knit",
    "my favorite smoothie is mango",
    "I enjoy bird watching",
    "the farmers market is open on Saturdays",
    "I'm starting a blog about my travels",
    "my favorite berry is strawberry",
    "I love going to the beach",
    "the museum exhibit was thought-provoking",
    "I'm learning to cook French cuisine",
    "my favorite pasta is spaghetti",
    "I enjoy visiting historical sites",
    "the yoga class was relaxing",
    "I'm learning to sew",
    "my favorite vegetable is broccoli",
    "I love going to farmers markets",
    "the art gallery had stunning paintings",
    "I'm learning Spanish online",
    "my favorite juice is orange juice",
    "I enjoy going to concerts",
    "the comedy show was hilarious",
    "I'm learning to play chess",
    "my favorite candy is chocolate",
    "I love going on road trips",
    "the ballet performance was graceful",
    "I'm learning to garden organically",
    "my favorite muffin is blueberry",
    "I enjoy visiting vineyards",
    "the jazz club had great music",
    "I'm learning to cook Italian food",
    "my favorite salad is Caesar",
    "I love going camping in the mountains",
    "the poetry reading was moving",
    "I'm learning to draw",
    "my favorite soup is tomato",
    "I enjoy visiting national parks",
    "the opera was spectacular",
    "I'm learning to code",
    "my favorite pizza topping is pepperoni",
    "I love going to the zoo",
    "the aquarium had amazing sea creatures",
    "I'm learning to cook Asian cuisine",
    "my favorite cookie is chocolate chip",
    "I enjoy visiting botanical gardens",
    "the symphony orchestra was incredible",
    "I'm learning to surf",
    "my favorite pie is apple",
    "I love going to the movies",
    "the planetarium show was fascinating",
    "I'm learning to cook Mexican food",
    "my favorite donut is glazed",
    "I enjoy visiting ancient ruins",
    "the circus was entertaining",
    "I'm learning to ski",
    "my favorite bagel is everything",
    "I love going to amusement parks",
    "the science museum had interactive exhibits",
    "I'm learning to snowboard",
    "my favorite latte is vanilla",
    "I enjoy visiting historical landmarks",
    "the theater production was outstanding",
    "I'm learning to cook Indian food",
    "my favorite cappuccino is dry",
    "I love going to the countryside",
    "the wine tasting was delightful",
    "I'm learning to meditate",
    "my favorite macchiato is caramel",
    "I enjoy going to the lake",
    "the pottery class was fun",
    "I'm learning to cook Mediterranean food",
    "my favorite espresso is double",
    "I love going to the mountains",
    "the cheese tasting was delicious",
    "I'm learning to play the guitar",
    "my favorite mocha is white chocolate",
    "I enjoy going to the forest",
    "the tea ceremony was peaceful",
    "I'm learning to cook Japanese food",
    "my favorite frappe is mocha",
    "I love going to the desert",
    "the flower arrangement workshop was creative",
    "I'm learning to cook Greek food",
    "my favorite smoothie bowl is acai",
    "I enjoy going to the coast",
    "the wine and paint night was entertaining",
    "I'm learning to cook Korean food",
    "my favorite juice cleanse is green juice",
    "I love going to the countryside",
    "the cooking class was informative",
    "I'm learning to cook Spanish food",
    "my favorite protein shake is chocolate",
    "I enjoy going to the meadow",
    "the photography workshop was inspiring",
    "I'm learning to cook Brazilian food",
    "my favorite energy drink is sugar-free",
    "I love going to the hills",
    "the dance class was energetic",
    "I'm learning to cook Thai food",
    "my favorite hot chocolate is dark chocolate",
    "I enjoy going to the valley",
    "the meditation retreat was rejuvenating",
    "I'm learning to cook Vietnamese food",
    "my favorite cider is apple cider",
    "I love going to the plains",
    "the yoga retreat was transformative",
    "I'm learning to cook Middle Eastern food",
    "my favorite lemonade is strawberry",
    "I enjoy going to the wetlands",
    "the spa day was relaxing",
    "I'm learning to cook African food",
    "my favorite iced tea is peach",
    "I love going to the savanna",
    "the wellness retreat was refreshing",
    "I'm learning to cook Caribbean food",
    "my favorite hot tea is Earl Grey",
    "I enjoy going to the tundra",
    "the mindfulness retreat was enlightening",
    "I'm learning to cook fusion food",
    "my favorite cold brew is vanilla",
    "I love going to the rainforest",
    "the silent retreat was peaceful",
    "I'm learning to cook modern food",
    "my favorite nitro brew is stout",
    "I enjoy going to the grasslands",
    "the digital detox was challenging but rewarding",
    "I'm learning to cook traditional food",
    "my favorite kombucha is ginger",
    "I love going to the highland",
    "the nature walk was invigorating",
    "I'm learning to cook ancient food",
    "my favorite chai is masala",
    "I enjoy going to the lowland",
    "the stargazing night was magical",
    "I'm learning to cook regional food",
    "my favorite matcha is ceremonial grade",
    "I love going to the woodland",
    "the bird watching tour was fascinating",
    "I'm learning to cook local food",
    "my favorite yerba mate is Argentine",
    "I enjoy going to the wetlands",
    "the wildlife safari was thrilling",
    "I'm learning to cook national food",
    "my favorite rooibos is vanilla",
    "I love going to the marshland",
    "the whale watching trip was incredible",
    "I'm learning to cook international food",
    "my favorite oolong is Tieguanyin",
    "I enjoy going to the peatland",
    "the dolphin watching tour was amazing",
    "I'm learning to cook global food",
    "my favorite pu-erh is aged",
    "I love going to the heathland",
    "the seal watching tour was delightful",
    "I'm learning to cook ethnic food",
    "my favorite white tea is silver needle",
    "I enjoy going to the cropland",
    "the penguin watching tour was adorable",
    "I'm learning to cook cultural food",
    "my favorite green tea is sencha",
    "I love going to the farmland",
    "the eagle watching tour was majestic",
    "I'm learning to cook heritage food",
    "my favorite black tea is Assam",
    "I enjoy going to the ranchland",
    "the hawk watching tour was impressive",
    "I'm learning to cook ancestral food",
    "my favorite herbal tea is peppermint",
    "I love going to the woodland",
    "the owl watching tour was mysterious",
    "I'm learning to cook native food",
    "my favorite fruit tea is berry",
    "I enjoy going to the forest",
    "the falcon watching tour was breathtaking",
    "I'm learning to cook indigenous food",
    "my favorite spiced tea is chai",
    "I love going to the jungle",
    "the parrot watching tour was colorful",
    "I'm learning to cook aboriginal food",
    "my favorite flowering tea is jasmine",
    "I enjoy going to the woods",
    "the toucan watching tour was exotic",
    "I'm learning to cook tribal food",
    "my favorite fermented tea is kombucha",
    "I love going to the grove",
    "the hummingbird watching tour was enchanting",
    "I'm learning to cook village food",
    "my favorite iced tea is lemon",
    "I enjoy going to the copse",
    "the flamingo watching tour was elegant",
    "I'm learning to cook countryside food",
    "my favorite sun tea is citrus",
    "I love going to the thicket",
    "the peacock watching tour was stunning",
    "I'm learning to cook rural food",
    "my favorite sweet tea is Southern style",
    "I enjoy going to the brake",
    "the swan watching tour was graceful",
    "I'm learning to cook urban food",
    "my favorite Thai tea is with boba",
    "I love going to the covert",
    "the heron watching tour was serene",
    "I'm learning to cook metropolitan food",
    "my favorite bubble tea is taro",
    "I enjoy going to the spinney",
    "the crane watching tour was majestic",
    "I'm learning to cook cosmopolitan food",
    "my favorite milk tea is Hong Kong style",
    "I love going to the wood",
    "the stork watching tour was impressive",
    "I'm learning to cook modern food",
    "my favorite cheese tea is cream cheese",
    "I enjoy going to the bush",
    "the pelican watching tour was amusing",
    "I'm learning to cook contemporary food",
    "my favorite fruit tea is peach",
    "I love going to the scrub",
    "the albatross watching tour was amazing",
    "I'm learning to cook fusion food",
    "my favorite iced coffee is cold brew",
    "I enjoy going to the moor",
    "the puffin watching tour was charming",
    "I'm learning to cook innovative food",
    "my favorite frozen coffee is blended",
    "I love going to the heath",
    "the puffin watching tour was delightful",
    "I'm learning to cook experimental food",
    "my favorite affogato is vanilla",
    "I enjoy going to the fell",
    "the puffin watching tour was entertaining",
    "I'm learning to cook avant-garde food",
    "my favorite espresso con panna is with whipped cream",
    "I love going to the down",
    "the puffin watching tour was fascinating",
    "I'm learning to cook molecular food",
    "my favorite romano is with cheese",
    "I enjoy going to the vale",
    "the puffin watching tour was incredible",
    "I'm learning to cook deconstructed food",
    "my favorite cappuccino is frothy",
    "I love going to the dale",
    "the puffin watching tour was memorable",
    "I'm learning to cook reconstructed food",
    "my favorite macchiato is strong",
    "I enjoy going to the glen",
    "the puffin watching tour was wonderful",
    "I'm learning to cook plated food",
    "my favorite cortado is equal parts",
    "I love going to the dell",
    "the puffin watching tour was spectacular",
    "I'm learning to cook tasting menu food",
    "my favorite lungo is extended",
    "I enjoy going to the hollow",
    "the puffin watching tour was extraordinary",
    "I'm learning to cook farm-to-table food",
    "my favorite doppio is double",
    "I love going to the valley",
    "the puffin watching tour was remarkable",
    "I'm learning to cook nose-to-tail food",
    "my favorite Americano is diluted",
    "I enjoy going to the basin",
    "the puffin watching tour was outstanding",
    "I'm learning to cook root-to-stem food",
    "my favorite long black is strong",
    "I love going to the bowl",
    "the puffin watching tour was exceptional",
    "I'm learning to cook plant-based food",
    "my favorite flat white is smooth",
    "I enjoy going to the crater",
    "the puffin watching tour was phenomenal",
    "I'm learning to cook vegan food",
    "my favorite piccolo is small",
    "I love going to the caldera",
    "the puffin watching tour was brilliant",
    "I'm learning to cook vegetarian food",
    "my favorite cortado is split",
    "I enjoy going to the canyon",
    "the puffin watching tour was superb",
    "I'm learning to cook pescatarian food",
    "my favorite Gibraltar is strong",
    "I love going to the gorge",
    "the puffin watching tour was stellar",
    "I'm learning to cook keto food",
    "my favorite breve is creamy",
    "I enjoy going to the ravine",
    "the puffin watching tour was glorious",
    "I'm learning to cook paleo food",
    "my favorite mocha is chocolatey",
    "I love going to the gulch",
    "the puffin watching tour was radiant",
    "I'm learning to cook Mediterranean food",
    "my favorite latte is mild",
    "I enjoy going to the coulee",
    "the puffin watching tour was luminous",
    "I'm learning to cook DASH food",
    "my favorite cappuccino is dry",
    "I love going to the arroyo",
    "the puffin watching tour was shining",
    "I'm learning to cook intermittent fasting food",
    "my favorite espresso is bold",
    "I enjoy going to the wash",
    "the puffin watching tour was glowing",
    "I'm learning to cook intuitive eating food",
    "my favorite macchiato is sweet",
    "I love going to the gully",
    "the puffin watching tour was sparkling",
    "I'm learning to cook mindful eating food",
    "my favorite americano is mild",
    "I enjoy going to the draw",
    "the puffin watching tour was glittering",
    "I'm learning to cook whole foods food",
    "my favorite long black is smooth",
    "I love going to the channel",
    "the puffin watching tour was twinkling",
    "I'm learning to cook clean eating food",
    "my favorite flat white is creamy",
    "I enjoy going to the trench",
    "the puffin watching tour was dazzling",
    "I'm learning to cook flexitarian food",
    "my favorite piccolo is intense",
    "I love going to the ditch",
    "the puffin watching tour was shimmering",
    "I'm learning to cook macrobiotic food",
    "my favorite cortado is balanced",
    "I enjoy going to the dike",
    "the puffin watching tour was gleaming",
    "I'm learning to cook raw food food",
    "my favorite Gibraltar is rich",
    "I love going to the levee",
    "the puffin watching tour was glistening",
    "I'm learning to cook juice cleanse food",
    "my favorite breve is thick",
    "I enjoy going to the embankment",
    "the puffin watching tour was lustrous",
    "I'm learning to cook detox food",
    "my favorite mocha is dark",
    "I love going to the bank",
    "the puffin watching tour was polished",
    "I'm learning to cook alkaline food",
    "my favorite latte is sweet",
    "I enjoy going to the shore",
    "the puffin watching tour was burnished",
    "I'm learning to cook anti-inflammatory food",
    "my favorite cappuccino is wet",
    "I love going to the beach",
    "the puffin watching tour was buffed",
    "I'm learning to cook low-carb food",
    "my favorite espresso is strong",
    "I enjoy going to the coast",
    "the puffin watching tour was waxed",
    "I'm learning to cook low-fat food",
    "my favorite macchiato is bold",
    "I love going to the seaside",
    "the puffin watching tour was rubbed",
    "I'm learning to cook high-protein food",
    "my favorite americano is strong",
    "I enjoy going to the strand",
    "the puffin watching tour was smoothed",
    "I'm learning to cook high-fiber food",
    "my favorite long black is bold",
    "I love going to the waterfront",
    "the puffin watching tour was sanded",
    "I'm learning to cook low-sodium food",
    "my favorite flat white is velvety",
    "I enjoy going to the bay",
    "the puffin watching tour was filed",
    "I'm learning to cook low-sugar food",
    "my favorite piccolo is concentrated",
    "I love going to the cove",
    "the puffin watching tour was rasped",
    "I'm learning to cook gluten-free food",
    "my favorite cortado is smooth",
    "I enjoy going to the inlet",
    "the puffin watching tour was ground",
    "I'm learning to cook dairy-free food",
    "my favorite Gibraltar is intense",
    "I love going to the sound",
    "the puffin watching tour was milled",
    "I'm learning to cook nut-free food",
    "my favorite breve is rich",
    "I enjoy going to the strait",
    "the puffin watching tour was crushed",
    "I'm learning to cook soy-free food",
    "my favorite mocha is sweet",
    "I love going to the channel",
    "the puffin watching tour was pulverized",
    "I'm learning to cook egg-free food",
    "my favorite latte is bold",
    "I enjoy going to the passage",
    "the puffin watching tour was powdered",
    "I'm learning to cook shellfish-free food",
    "my favorite cappuccino is frothy",
    "I love going to the narrows",
    "the puffin watching tour was granulated",
    "I'm learning to cook fish-free food",
    "my favorite espresso is intense",
    "I enjoy going to the throat",
    "the puffin watching tour was shredded",
    "I'm learning to cook meat-free food",
    "my favorite macchiato is smooth",
    "I love going to the neck",
    "the puffin watching tour was grated",
    "I'm learning to cook animal-product-free food",
    "my favorite americano is smooth",
    "I enjoy going to the bottleneck",
    "the puffin watching tour was shaved",
    "I'm learning to cook whole-food plant-based food",
    "my favorite long black is rich",
    "I love going to the isthmus",
    "the puffin watching tour was sliced",
    "I'm learning to cook starch-free food",
    "my favorite flat white is rich",
    "I enjoy going to the peninsula",
    "the puffin watching tour was diced",
    "I'm learning to cook sugar-free food",
    "my favorite piccolo is bold",
    "I love going to the cape",
    "the puffin watching tour was cubed",
    "I'm learning to cook salt-free food",
    "my favorite cortado is rich",
    "I enjoy going to the point",
    "the puffin watching tour was chopped",
    "I'm learning to cook fat-free food",
    "my favorite Gibraltar is bold",
    "I love going to the promontory",
    "the puffin watching tour was minced",
    "I'm learning to cook calorie-restricted food",
    "my favorite breve is bold",
    "I enjoy going to the headland",
    "the puffin watching tour was pureed",
    "I'm learning to cook portion-controlled food",
    "my favorite mocha is bold",
    "I love going to the bluff",
    "the puffin watching tour was mashed",
    "I'm learning to cook timed-eating food",
    "my favorite latte is rich",
    "I enjoy going to the cliff",
    "the puffin watching tour was pressed",
    "I'm learning to cook intuitive portion control",
    "my favorite cappuccino is rich",
    "I love going to the precipice",
    "the puffin watching tour was juiced",
    "I'm learning to cook hunger-based eating",
    "my favorite espresso is rich",
    "I enjoy going to the ledge",
    "the puffin watching tour was squeezed",
    "I'm learning to cook satiety-based eating",
    "my favorite macchiato is rich",
    "I love going to the shelf",
    "the puffin watching tour was extracted",
    "I'm learning to cook craving-based eating",
    "my favorite americano is rich",
    "I enjoy going to the terrace",
    "the puffin watching tour was brewed",
    "I'm learning to cook emotional-eating management",
    "my favorite long black is full",
    "I love going to the plateau",
    "the puffin watching tour was steeped",
    "I'm learning to cook stress-eating management",
    "my favorite flat white is full",
    "I enjoy going to the mesa",
    "the puffin watching tour was infused",
    "I'm learning to cook boredom-eating management",
    "my favorite piccolo is full",
    "I love going to the tableland",
    "the puffin watching tour was decocted",
    "I'm learning to cook social-eating management",
    "my favorite cortado is full",
    "I enjoy going to the butte",
    "the puffin watching tour was percolated",
    "I'm learning to cook celebration-eating management",
    "my favorite Gibraltar is full",
    "I love going to the pinnacle",
    "the puffin watching tour was filtered",
    "I'm learning to cook holiday-eating management",
    "my favorite breve is full",
    "I enjoy going to the peak",
    "the puffin watching tour was strained",
    "I'm learning to cook vacation-eating management",
    "my favorite mocha is full",
    "I love going to the summit",
    "the puffin watching tour was sieved",
    "I'm learning to cook work-eating management",
    "my favorite latte is full",
    "I enjoy going to the crest",
    "the puffin watching tour was clarified",
    "I'm learning to cook school-eating management",
    "my favorite cappuccino is full",
    "I love going to the crown",
    "the puffin watching tour was purified",
    "I'm learning to cook party-eating management",
    "my favorite espresso is full",
    "I enjoy going to the top",
    "the puffin watching tour was refined",
    "I'm learning to cook restaurant-eating management",
    "my favorite macchiato is full",
    "I love going to the apex",
    "the puffin watching tour was distilled",
    "I'm learning to cook fast-food-eating management",
    "my favorite americano is full",
    "I enjoy going to the vertex",
    "the puffin watching tour was rectified",
    "I'm learning to cook processed-food-eating management",
    "my favorite long black is complete",
    "I love going to the zenith",
    "the puffin watching tour was concentrated",
    "I'm learning to cook organic-food-eating management",
    "my favorite flat white is complete",
    "I enjoy going to the acme",
    "the puffin watching tour was evaporated",
    "I'm learning to cook local-food-eating management",
    "my favorite piccolo is complete",
    "I love going to the peak",
    "the puffin watching tour was condensed",
    "I'm learning to cook seasonal-food-eating management",
    "my favorite cortado is complete",
    "I enjoy going to the maximum",
    "the puffin watching tour was reduced",
    "I'm learning to cook sustainable-food-eating management",
    "my favorite Gibraltar is complete",
    "I love going to the ultimate",
    "the puffin watching tour was thickened",
    "I'm learning to cook ethical-food-eating management",
    "my favorite breve is complete",
    "I enjoy going to the supreme",
    "the puffin watching tour was thinned",
    "I'm learning to cook fair-trade-food-eating management",
    "my favorite mocha is complete",
    "I love going to the paramount",
    "the puffin watching tour was diluted",
    "I'm learning to cook plant-based-protein food",
    "my favorite latte is complete",
    "I enjoy going to the utmost",
    "the puffin watching tour was watered",
    "I'm learning to cook insect-protein food",
    "my favorite cappuccino is complete",
    "I love going to the extreme",
    "the puffin watching tour was mixed",
    "I'm learning to cook lab-grown-meat food",
    "my favorite espresso is complete",
    "I enjoy going to the radical",
    "the puffin watching tour was blended",
    "I'm learning to cook 3D-printed-food food",
    "my favorite macchiato is complete",
    "I love going to the drastic",
    "the puffin watching tour was combined",
    "I'm learning to cook algae-based-protein food",
    "my favorite americano is complete",
    "I enjoy going to the severe",
    "the puffin watching tour was merged",
    "I'm learning to cook fungal-protein food",
    "my favorite long black is flawless",
    "I love going to the stern",
    "the puffin watching tour was fused",
    "I'm learning to cook bacterial-protein food",
    "my favorite flat white is flawless",
    "I enjoy going to the austere",
    "the puffin watching tour was united",
    "I'm learning to cook yeast-protein food",
    "my favorite piccolo is flawless",
    "I love going to the rigorous",
    "the puffin watching tour was joined",
    "I'm learning to cook mycoprotein food",
    "my favorite cortado is flawless",
    "I enjoy going to the stringent",
    "the puffin watching tour was linked",
    "I'm learning to cook textured-vegetable-protein food",
    "my favorite Gibraltar is flawless",
    "I love going to the firm",
    "the puffin watching tour was connected",
    "I'm learning to cook seitan-based food",
    "my favorite breve is flawless",
    "I enjoy going to the strict",
    "the puffin watching tour was attached",
    "I'm learning to cook tempeh-based food",
    "my favorite mocha is flawless",
    "I love going to the tough",
    "the puffin watching tour was bound",
    "I'm learning to cook tofu-based food",
    "my favorite latte is flawless",
    "I enjoy going to the harsh",
    "the puffin watching tour was tied",
    "I'm learning to cook natto-based food",
    "my favorite cappuccino is flawless",
    "I love going to the grim",
    "the puffin watching tour was knotted",
    "I'm learning to cook miso-based food",
    "my favorite espresso is flawless",
    "I enjoy going to the bleak",
    "the puffin watching tour was laced",
    "I'm learning to cook edamame-based food",
    "my favorite macchiato is flawless",
    "I love going to the dismal",
    "the puffin watching tour was threaded",
    "I'm learning to cook soy-based food",
    "my favorite americano is flawless",
    "I enjoy going to the dreary",
    "the puffin watching tour was woven",
    "I'm learning to cook legume-based food",
    "my favorite long black is ideal",
    "I love going to the cheerless",
    "the puffin watching tour was spun",
    "I'm learning to cook pulse-based food",
    "my favorite flat white is ideal",
    "I enjoy going to the joyless",
    "the puffin watching tour was knitted",
    "I'm learning to cook bean-based food",
    "my favorite piccolo is ideal",
    "I love going to the somber",
    "the puffin watching tour was crocheted",
    "I'm learning to cook lentil-based food",
    "my favorite cortado is ideal",
    "I enjoy going to the melancholy",
    "the puffin watching tour was embroidered",
    "I'm learning to cook chickpea-based food",
    "my favorite Gibraltar is ideal",
    "I love going to the mournful",
    "the puffin watching tour was quilted",
    "I'm learning to cook pea-protein food",
    "my favorite breve is ideal",
    "I enjoy going to the sorrowful",
    "the puffin watching tour was sewn",
    "I'm learning to cook quinoa-protein food",
    "my favorite mocha is ideal",
    "I love going to the woeful",
    "the puffin watching tour was stitched",
    "I'm learning to cook amaranth-protein food",
    "my favorite latte is ideal",
    "I enjoy going to the doleful",
    "the puffin watching tour was tailored",
    "I'm learning to cook buckwheat-protein food",
    "my favorite cappuccino is ideal",
    "I love going to the rueful",
    "the puffin watching tour was hemmed",
    "I'm learning to cook hemp-protein food",
    "my favorite espresso is ideal",
    "I enjoy going to the lugubrious",
    "the puffin watching tour was seamed",
    "I'm learning to cook chia-protein food",
    "my favorite macchiato is ideal",
    "I love going to the plaintive",
    "the puffin watching tour was tacked",
    "I'm learning to cook flax-protein food",
    "my favorite americano is ideal",
    "I enjoy going to the piteous",
    "the puffin watching tour was basted",
    "I'm learning to cook pumpkin-seed-protein food",
    "my favorite long black is optimal",
    "I love going to the pathetic",
    "the puffin watching tour was quilted",
    "I'm learning to cook sunflower-seed-protein food",
    "my favorite flat white is optimal",
    "I enjoy going to the moving",
    "the puffin watching tour was patched",
    "I'm learning to cook sesame-seed-protein food",
    "my favorite piccolo is optimal",
    "I love going to the touching",
    "the puffin watching tour was mended",
    "I'm learning to cook poppy-seed-protein food",
    "my favorite cortado is optimal",
    "I enjoy going to the affecting",
    "the puffin watching tour was repaired",
    "I'm learning to cook almond-protein food",
    "my favorite Gibraltar is optimal",
    "I love going to the poignant",
    "the puffin watching tour was restored",
    "I'm learning to cook walnut-protein food",
    "my favorite breve is optimal",
    "I enjoy going to the heartrending",
    "the puffin watching tour was renewed",
    "I'm learning to cook pecan-protein food",
    "my favorite mocha is optimal",
    "I love going to the heartbreaking",
    "the puffin watching tour was revived",
    "I'm learning to cook cashew-protein food",
    "my favorite latte is optimal",
    "I enjoy going to the heartwarming",
    "the puffin watching tour was refreshed",
    "I'm learning to cook pistachio-protein food",
    "my favorite cappuccino is optimal",
    "I love going to the heartening",
    "the puffin watching tour was reinvigorated",
    "I'm learning to cook macadamia-protein food",
    "my favorite espresso is optimal",
    "I enjoy going to the uplifting",
    "the puffin watching tour was revitalized",
    "I'm learning to cook brazil-nut-protein food",
    "my favorite macchiato is optimal",
    "I love going to the inspiring",
    "the puffin watching tour was rejuvenated",
    "I'm learning to cook chestnut-protein food",
    "my favorite americano is optimal",
    "I enjoy going to the encouraging",
    "the puffin watching tour was regenerated",
    "I'm learning to cook acorn-protein food",
    "my favorite long black is prime",
    "I love going to the motivating",
    "the puffin watching tour was renewed",
    "I'm learning to cook pine-nut-protein food",
    "my favorite flat white is prime",
    "I enjoy going to the stimulating",
    "the puffin watching tour was awakened",
    "I'm learning to cook hazelnut-protein food",
    "my favorite piccolo is prime",
    "I love going to the exciting",
    "the puffin watching tour was stirred",
    "I'm learning to cook pecan-protein food",
    "my favorite cortado is prime",
    "I enjoy going to the invigorating",
    "the puffin watching tour was roused",
    "I'm learning to cook coconut-protein food",
    "my favorite Gibraltar is prime",
    "I love going to the electrifying",
    "the puffin watching tour was energized",
    "I'm learning to cook date-protein food",
    "my favorite breve is prime",
    "I enjoy going to the exhilarating",
    "the puffin watching tour was activated",
    "I'm learning to cook fig-protein food",
    "my favorite mocha is prime",
    "I love going to the thrilling",
    "the puffin watching tour was powered",
    "I'm learning to cook raisin-protein food",
    "my favorite latte is prime",
    "I enjoy going to the intoxicating",
    "the puffin watching tour was charged",
    "I'm learning to cook prune-protein food",
    "my favorite cappuccino is prime",
    "I love going to the heady",
    "the puffin watching tour was fueled",
    "I'm learning to cook apricot-protein food",
    "my favorite espresso is prime",
    "I enjoy going to the uplifting",
    "the puffin watching tour was ignited",
    "I'm learning to cook peach-protein food",
    "my favorite macchiato is prime",
    "I love going to the elevating",
    "the puffin watching tour was lit",
    "I'm learning to cook pear-protein food",
    "my favorite americano is prime",
    "I enjoy going to the raising",
    "the puffin watching tour was fired",
    "I'm learning to cook apple-protein food",
    "my favorite long black is premium",
    "I love going to the lifting",
    "the puffin watching tour was sparked",
    "I'm learning to cook banana-protein food",
    "my favorite flat white is premium",
    "I enjoy going to the hoisting",
    "the puffin watching tour was kindled",
    "I'm learning to cook mango-protein food",
    "my favorite piccolo is premium",
    "I love going to the boosting",
    "the puffin watching tour was inflamed",
    "I'm learning to cook pineapple-protein food",
    "my favorite cortado is premium",
    "I enjoy going to the enhancing",
    "the puffin watching tour was ignited",
    "I'm learning to cook papaya-protein food",
    "my favorite Gibraltar is premium",
    "I love going to the augmenting",
    "the puffin watching tour was lit",
    "I'm learning to cook watermelon-protein food",
    "my favorite breve is premium",
    "I enjoy going to the amplifying",
    "the puffin watching tour was sparked",
    "I'm learning to cook cantaloupe-protein food",
    "my favorite mocha is premium",
    "I enjoy going to the magnifying",
    "the puffin watching tour was kindled",
    "I'm learning to cook honeydew-protein food",
    "my favorite latte is premium",
    "I love going to the intensifying",
    "the puffin watching tour was stoked",
    "I'm learning to cook strawberry-protein food",
    "my favorite cappuccino is premium",
    "I enjoy going to the deepening",
    "the puffin watching tour was fed",
    "I'm learning to cook blueberry-protein food",
    "my favorite espresso is premium",
    "I love going to the enriching",
    "the puffin watching tour was fueled",
    "I'm learning to cook raspberry-protein food",
    "my favorite macchiato is premium",
    "I enjoy going to the enhancing",
    "the puffin watching tour was powered",
    "I'm learning to cook blackberry-protein food",
    "my favorite americano is premium",
    "I love going to the improving",
    "the puffin watching tour was charged",
    "I'm learning to cook cranberry-protein food",
    "my favorite long black is superior",
    "I enjoy going to the upgrading",
    "the puffin watching tour was energized",
    "I'm learning to cook cherry-protein food",
    "my favorite flat white is superior",
    "I love going to the refining",
    "the puffin watching tour was refreshed",
    "I'm learning to cook grape-protein food",
    "my favorite piccolo is superior",
    "I enjoy going to the polishing",
    "the puffin watching tour was renewed",
    "I'm learning to cook orange-protein food",
    "my favorite cortado is superior",
    "I love going to the perfecting",
    "the puffin watching tour was revived",
    "I'm learning to cook lemon-protein food",
    "my favorite Gibraltar is superior",
    "I enjoy going to the mastering",
    "the puffin watching tour was restored",
    "I'm learning to cook lime-protein food",
    "my favorite breve is superior",
    "I love going to the conquering",
    "the puffin watching tour was rejuvenated",
    "I'm learning to cook grapefruit-protein food",
    "my favorite mocha is superior",
    "I enjoy going to the dominating",
    "the puffin watching tour was reinvigorated",
    "I'm learning to cook kiwi-protein food",
    "my favorite latte is superior",
    "I love going to the ruling",
    "the puffin watching tour was revitalized",
    "I'm learning to cook passion-fruit-protein food",
    "my favorite cappuccino is superior",
    "I enjoy going to the leading",
    "the puffin watching tour was regenerated",
    "I'm learning to cook dragon-fruit-protein food",
    "my favorite espresso is superior",
    "I love going to the guiding",
    "the puffin watching tour was awakened",
    "I'm learning to cook pomegranate-protein food",
    "my favorite macchiato is superior",
    "I enjoy going to the directing",
    "the puffin watching tour was stirred",
    "I'm learning to cook guava-protein food",
    "my favorite americano is superior",
    "I love going to the managing",
    "the puffin watching tour was roused",
    "I'm learning to cook lychee-protein food",
    "my favorite long black is excellent",
    "I enjoy going to the supervising",
    "the puffin watching tour was energized",
    "I'm learning to cook longan-protein food",
    "my favorite flat white is excellent",
    "I love going to the overseeing",
    "the puffin watching tour was activated",
    "I'm learning to cook rambutan-protein food",
    "my favorite piccolo is excellent",
    "I enjoy going to the coordinating",
    "the puffin watching tour was powered",
    "I'm learning to cook durian-protein food",
    "my favorite cortado is excellent",
    "I love going to the organizing",
    "the puffin watching tour was charged",
    "I'm learning to cook jackfruit-protein food",
    "my favorite Gibraltar is excellent",
    "I enjoy going to the arranging",
    "the puffin watching tour was fueled",
    "I'm learning to cook breadfruit-protein food",
    "my favorite breve is excellent",
    "I love going to the planning",
    "the puffin watching tour was ignited",
    "I'm learning to cook soursop-protein food",
    "my favorite mocha is excellent",
    "I enjoy going to the scheduling",
    "the puffin watching tour was lit",
    "I'm learning to cook cherimoya-protein food",
    "my favorite latte is excellent",
    "I love going to the timing",
    "the puffin watching tour was fired",
    "I'm learning to cook sapote-protein food",
    "my favorite cappuccino is excellent",
    "I enjoy going to the sequencing",
    "the puffin watching tour was sparked",
    "I'm learning to cook tamarind-protein food",
    "my favorite espresso is excellent",
    "I love going to the pacing",
    "the puffin watching tour was kindled",
    "I'm learning to cook star-fruit-protein food",
    "my favorite macchiato is excellent",
    "I enjoy going to the metering",
    "the puffin watching tour was stoked",
    "I'm learning to cook persimmon-protein food",
    "my favorite americano is excellent",
    "I love going to the regulating",
    "the puffin watching tour was fed",
    "I'm learning to cook quince-protein food",
    "my favorite long black is outstanding",
    "I enjoy going to the calibrating",
    "the puffin watching tour was fueled",
    "I'm learning to cook mulberry-protein food",
    "my favorite flat white is outstanding",
    "I love going to the adjusting",
    "the puffin watching tour was powered",
    "I'm learning to cook elderberry-protein food",
    "my favorite piccolo is outstanding",
    "I enjoy going to the tuning",
    "the puffin watching tour was charged",
    "I'm learning to cook goji-berry-protein food",
    "my favorite cortado is outstanding",
    "I love going to the aligning",
    "the puffin watching tour was energized",
    "I'm learning to cook acai-berry-protein food",
    "my favorite Gibraltar is outstanding",
    "I enjoy going to the positioning",
    "the puffin watching tour was activated",
    "I'm learning to cook camu-camu-protein food",
    "my favorite breve is outstanding",
    "I love going to the orienting",
    "the puffin watching tour was powered",
    "I'm learning to cook cupuacu-protein food",
    "my favorite mocha is outstanding",
    "I enjoy going to the directing",
    "the puffin watching tour was charged",
    "I'm learning to cook graviola-protein food",
    "my favorite latte is outstanding",
    "I love going to the guiding",
    "the puffin watching tour was fueled",
    "I'm learning to cook soursop-leaf-protein food",
]


def generate_noise_pool() -> list[str]:
    """Generate a large pool of non-intent bearing statements."""
    pool = set()
    for topic in NON_INTENT_TOPICS:
        for polite in POLITE:
            if polite.endswith(","):
                pool.add(f"{polite} {topic}.")
            else:
                pool.add(f"{polite} {topic}.")
            pool.add(f"{topic}.")
    return sorted(pool)


def main():
    pool = generate_noise_pool()
    print(f"Generated noise pool size: {len(pool)} unique statements")
    with OUTPUT.open("w", encoding="utf-8") as f:
        json.dump({"non_intent_statements": pool}, f, indent=2, ensure_ascii=False)
    print(f"Saved to {OUTPUT}")


if __name__ == "__main__":
    main()
